#ifndef DATA_H
#define DATA_H
#include <stdio.h>

const char *strings[]={
    "FMEE Aeroport de La Reunion Roland Garros",
    "FMEP Aeroport de Saint-Pierre - Pierrefonds",
    "LF34 Base aerienne de Moussoulens",
    "LF7622 Aerodrome d'Yvetot",
    "LFAB Aerodrome de Dieppe - Saint-Aubin",
    "LFAC Aeroport de Calais - Dunkerque",
    "LFAD Aerodrome de Compiegne - Margny",
    "LFAE Aerodrome d'Eu - Mers - Le Treport",
    "LFAF Aerodrome de Laon - Chambry",
    "LFAG Aeroport de Peronne - Saint-Quentin",
    "LFAI Aeroport de Nangis Les Loges",
    "LFAJ Aeroport d'Argentan",
    "LFAK Aerodrome de Dunkerque - Les Moeres",
    "LFAL Aerodrome de La Fleche - Thoree-les-Pins",
    "LFAM Aeroport de Berck sur Mer",
    "LFAO Aerodrome de Bagnoles-de-l'Orne - Couterne",
    "LFAP Aerodrome de Rethel - Perthes",
    "LFAQ Aerodrome d'Albert - Bray",
    "LFAR Aerodrome de Montdidier",
    "LFAS Aerodrome de Falaise Mont d'Eraines",
    "LFAT Aeroport du Touquet Cote d'Opale",
    "LFAU Aerodrome de Vauville",
    "LFAV Aeroport de Valenciennes - Denain",
    "LFAW Aerodrome de Villerupt",
    "LFAX Aeroport de Mortagne au Perche",
    "LFAY Aeroport d'Amiens - Glisy",
    "LFBA Aeroport Agen - La Garenne",
    "LFBC Base aerienne de Cazaux",
    "LFBD Aeroport de Bordeaux - Merignac",
    "LFBE Aeroport Bergerac - Roumaniere",
    "LFBF Aeroport de Francazal - Toulouse",
    "LFBG Base aerienne 709 Cognac - Chateaubernard",
    "LFBH Aeroport de La Rochelle - ile de Re",
    "LFBI Aeroport de Poitiers - Biard",
    "LFBJ Aeroport de Saint-Junien Maryse Bastie",
    "LFBK Aeroport de Montlucon Gueret",
    "LFBL Aeroport de Limoges Bellegarde",
    "LFBM Base aerienne 118 Mont de Marsan",
    "LFBN Aerodrome de Niort Souche",
    "LFBO Aeroport Toulouse Blagnac",
    "LFBP Aeroport Pau Pyrenees",
    "LFBR Aerodrome de Muret - Lherm",
    "LFBS Aerodrome des Grands Lacs",
    "LFBT Aeroport de Tarbes Lourdes Pyrenees",
    "LFBU Aeroport international Angouleme - Cognac",
    "LFBX Aeroport Perigueux Bassillac",
    "LFBY Aeroport de Dax - Seyresse",
    "LFBZ Aeroport de Biarritz Bayonne Anglet (BBA)",
    "LFCA Aeroport de Chatellerault Targe",
    "LFCB Aeroport de Bagneres de Luchon",
    "LFCC Aeroport de Cahors - Lalbenque",
    "LFCD Aeroport d'Andernos les Bains",
    "LFCE Aeroport de Gueret - Saint-Laurent",
    "LFCF Aerodrome de Figeac - Livernon",
    "LFCG Aerodrome de Saint-Girons - Antichan",
    "LFCH Aeroport d'Arcachon - La Teste-de-Buch",
    "LFCI Aerodrome d'Albi - Le Sequestre",
    "LFCJ Aeroport de Jonzac - Neulles",
    "LFCK Aeroport de Castres - Mazamet",
    "LFCL Aeroport de Toulouse - Lasbordes",
    "LFCM Aerodrome de Millau Larzac",
    "LFCN Aeroport de Nogaro",
    "LFCO Aeroport d'Oloron - Herrere",
    "LFCP Aeroport de Pons - Avy",
    "LFCQ Aeroport de Graulhet - Montdragon",
    "LFCR Aeroport de Rodez - Marcillac",
    "LFCS Aeroport de Bordeaux - Leognan - Saucats",
    "LFCT Aeroport de Thouars",
    "LFCU Aerodrome d'Ussel - Thalamy",
    "LFCV Aeroport de Villefranche de Rouergue",
    "LFCW Aerodrome de Villeneuve sur Lot",
    "LFCX Aeroport de Castelsarrasin - Moissac",
    "LFCY Aerodrome de Royan - Medis",
    "LFCZ Aeroport de Mimizan",
    "LFDA Aeroport d'Aire sur l'Adour",
    "LFDB Aeroport de Montauban",
    "LFDC Aeroport de Montendre - Marcillac",
    "LFDE Aeroport d'Aigletons",
    "LFDF Aeroport de Sainte-Foy la Grande",
    "LFDG Aeroport de Gaillac - Lisle-sur-Tarn",
    "LFDH Aeroport d'Auch Lamothe",
    "LFDI Aerodrome de Libourne - Artigues-de-Lussac",
    "LFDJ Aerodrome de Pamiers - Les Pujols",
    "LFDK Aeroport de Soulac sur Mer",
    "LFDL Aeroport de Loudun",
    "LFDM Aeroport de Marmande - Virazeil",
    "LFDN Aeroport de Rochefort - Saint-Agnant",
    "LFDP Aeroport de Saint-Pierre d'Oleron",
    "LFDQ Aerodrome de Castelnau Magnoac",
    "LFDR Aeroport de La Reole - Floudes",
    "LFDS Aeroport de Sarlat - Domme",
    "LFDT Aerodrome de Tarbes - Laloubere",
    "LFDU Aeroport de Lesparre - Saint-Laurent de Medoc",
    "LFDV Aeroport de Couhe Verac",
    "LFDW Aeroport de Chauvigny",
    "LFDX Aeroport de Fumel - Montayral",
    "LFDY Aerodrome de Bordeaux - Yvrac",
    "LFDZ Aeroport Condat sur Vezere",
    "LFEA Aeroport de Belle ile",
    "LFEB Aeroport de Dinan - Trelivan",
    "LFEC Aeroport d'Ouessant",
    "LFED Aeroport de Pontivy",
    "LFEF Aeroport d'Amboise - Dierre",
    "LFEG Aeroport d'Argenton sur Creuse",
    "LFEH Aerodrome d'Aubigny sur Nere",
    "LFEI Aeroport de Briare Chatillon",
    "LFEJ Aeroport de Chateauroux - Villers",
    "LFEK Aeroport d'Issoudun Le Fay",
    "LFEL Aeroport du Blanc",
    "LFEM Aeroport de Montargis - Vimory",
    "LFEN Aeroport de Tours - Sorigny",
    "LFEP Aerodrome de Pouilly - Maconge",
    "LFEQ Aeroport de Quiberon",
    "LFER Aeroport de Redon - Bains-sur-Oust",
    "LFES Aeroport de Guiscriff - Scaer",
    "LFET Aeroport de Til Chatel",
    "LFEU Aeroport de Bar-le-Duc - Les Hauts-de-Chee",
    "LFEV Aerodrome de Gray - Saint-Adrien",
    "LFEW Aeroport de Saulieu - Liernais",
    "LFEX Aerodrome de Nancy - Azelot",
    "LFEY Aeroport de l'Ile d'Yeu",
    "LFEZ Aerodrome de Nancy - Malzeville",
    "LFFB Aerodrome de Buno - Bonnevaux",
    "LFFC Aerodrome de Mantes - Cherence",
    "LFFD Aerodrome de Saint-Andre de l'Eure",
    "LFFE Aerodrome d'Enghien - Moisselles",
    "LFFG Aerodrome de La Ferte-Gaucher",
    "LFFH Aerodrome de Chateau-Thierry - Belleau",
    "LFFI Aeroport d'Ancenis",
    "LFFJ Aerodrome de Joinville - Mussey",
    "LFFK Aeroport de Fontenay le Comte",
    "LFFL Aerodrome de Bailleau - Armenonville",
    "LFFM Aerodrome de Lamotte Beuvron",
    "LFFN Aeroport de Brienne le Chateau",
    "LFFP Aerodrome de Pithiviers",
    "LFFQ Aerodrome de La Ferte Alais",
    "LFFR Aerodrome de Bar sur Seine",
    "LFFT Aerodrome de Neufchateau Rouceux",
    "LFFU Aerodrome de Chateauneuf sur Cher",
    "LFFV Aerodrome de Vierzon - Mereau",
    "LFFW Aeroport de Montaigu - Saint-Georges",
    "LFFX Aerodrome de Tournus - Cuisery",
    "LFFY Aerodrome d'etrepagny",
    "LFFZ Aeroport de Sezanne - Saint-Remy",
    "LFGA Aeroport de Colmar - Houssen",
    "LFGB Aerodrome de Mulhouse - Habsheim",
    "LFGC Aerodrome de Strasbourg - Neuhof",
    "LFGD Aerodrome d'Arbois",
    "LFGE Aeroport d'Avallon",
    "LFGF Aeroport de Beaune Challanges",
    "LFGG Aeroport de Belfort - Chaux",
    "LFGH Aeroport de Cosne sur Loire",
    "LFGI Aeroport de Dijon - Darois",
    "LFGJ Aeroport de Dole - Tavaux",
    "LFGK Aeroport de Joigny",
    "LFGL Aeroport de Lons-le-Saunier - Courlaoux",
    "LFGM Aeroport de Montceau-les-Mines - Pouilloux",
    "LFGN Aeroport de Paray le Monial",
    "LFGO Aeroport de Pont sur Yonne",
    "LFGP Aeroport de Saint-Florentin - Cheu",
    "LFGQ Aeroport de Semur en Auxois",
    "LFGR Aeroport de Doncourt les Conflans",
    "LFGS Aeroport de Longuyon - Villette",
    "LFGT Aeroport de Sarrebourg - Buhl",
    "LFGU Aeroport de Sarreguemines Neunkirch",
    "LFGW Aerodrome de Verdun Le Rozelier",
    "LFGX Aerodrome de Champagnole - Crotenay",
    "LFGY Aerodrome de Saint-Die - Remomeix",
    "LFGZ Aerodrome de Nuits Saint-Georges",
    "LFHA Aeroport d'Issoire - Le Broc",
    "LFHC Aerodrome de Perouges - Meximieux",
    "LFHD Aeroport de Pierrelatte",
    "LFHE Aeroport de Romans - Saint-Paul",
    "LFHF Aerodrome de Ruoms",
    "LFHG Aerodrome de Saint-Chamond - L'Horme",
    "LFHH Aeroport de Vienne Reventin",
    "LFHI Aerodrome de Morestel",
    "LFHJ Aerodrome de Lyon - Corbas",
    "LFHL Aeroport de Langogne - Lesperon",
    "LFHM Aerodrome de Megeve",
    "LFHN Aerodrome de Bellegarde Vouvray",
    "LFHO Aeroport d'Aubenas Ardeche meridionale",
    "LFHP Aeroport du Puy - Loudes",
    "LFHQ Aeroport de Saint-Flour - Coltines",
    "LFHR Aeroport de Brioude - Beaumont",
    "LFHS Aerodrome de Bourg - Ceyzeriat",
    "LFHT Aeroport d'Ambert Le Poyet",
    "LFHU Altiport de l'Alpe d'Huez",
    "LFHV Aeroport de Villefranche - Tarare",
    "LFHW Aerodrome de Belleville - Villie-Morgon",
    "LFHX Aerodrome de Lapalisse - Perigny",
    "LFHY Aerodrome de Moulins - Montbeugny",
    "LFHZ Aerodrome de Sallanches Mont Blanc",
    "LFIB Aerodrome de Belves - Saint-Pardoux",
    "LFID Aeroport de Condom - Valence-sur-Baise",
    "LFIF Aerodrome de Saint-Affrique - Belmont",
    "LFIG Aerodrome de Cassagnes - Begonhes",
    "LFIH Aeroport de Chalais",
    "LFIK Aerodrome de Riberac - Saint-Aulaye",
    "LFIL Aerodrome de Rion des Landes",
    "LFIM Aeroport de Saint-Gaudens - Montrejeau",
    "LFIP Aerodrome de Peyresourde - Balestas",
    "LFIR Aerodrome de Revel - Montgey",
    "LFIT Aerodrome de Toulouse - Bourg Saint-Bernard",
    "LFIV Aerodrome de Vendays - Montalivet",
    "LFIX Aerodrome d'Itxassou",
    "LFIY Aerodrome de Saint-Jean d'Angely - Saint-Denis du Pin",
    "LFJA Aerodrome de Chaumont - Semoutiers",
    "LFJB Aeroport de Mauleon",
    "LFJC Aeroport de Clamecy",
    "LFJD Aerodrome de Corlier",
    "LFJE Aerodrome de La Motte Chalancon",
    "LFJF Aerodrome d'Aubenasson",
    "LFJH Aerodrome de Cazeres - Palaminy",
    "LFJI Aerodrome de Marennes",
    "LFJL Aeroport Metz Nancy Lorraine",
    "LFJR Angers Loire Aeroport",
    "LFJS Aeroport de Soissons - Courmelles",
    "LFJT Aerodrome de Tours - Le Louroux",
    "LFJU Aerodrome de Lurcy - Levis",
    "LFJY Chambley-Bussieres Air Base",
    "LFKA Aerodrome d'Albertville",
    "LFKB Aeroport de Bastia Poretta",
    "LFKC Aeroport de Calvi Sainte-Catherine",
    "LFKD Aerodrome de Sollieres - Sardieres",
    "LFKE Aerodrome de Saint-Jean en Royans",
    "LFKF Aeroport de Figari Sud Corse",
    "LFKG Aerodrome de Ghisonaccia Alzitone",
    "LFKH Aerodrome de Saint-Jean d'Avelanne",
    "LFKJ Aeroport d'Ajaccio Napoleon Bonaparte",
    "LFKL Aerodrome de Lyon - Brindas",
    "LFKM Aerodrome de Saint-Galmier",
    "LFKO Aerodrome de Propriano",
    "LFKP Aerodrome de La Tour-du-Pin - Cessieu",
    "LFKR Aerodrome de Saint-Remy de Maurienne",
    "LFKS Base aerienne 126 de Solenzara",
    "LFKT Aerodrome de Corte",
    "LFKX Aerodrome de Meribel",
    "LFKY Aerodrome de Belley - Peyrieu",
    "LFLA Aeroport d'Auxerre - Branches",
    "LFLB Aeroport de Chambery - Savoie",
    "LFLC Aeroport de Clermont-Ferrand Auvergne",
    "LFLD Aeroport de Bourges",
    "LFLE Aeroport de Chambery - Challes-les-Eaux",
    "LFLG Aerodrome de Grenoble - Le Versoud",
    "LFLH Aeroport de Chalon - Champforgeuil",
    "LFLI Aerodrome d'Annemasse",
    "LFLJ Aerodrome de Courchevel",
    "LFLK Aerodrome d'Oyonnax - Arbent",
    "LFLL Aeroport Lyon Saint-Exupery",
    "LFLM Aeroport de Macon - Charnay",
    "LFLN Aeroport de Saint-Yan",
    "LFLO Aeroport de Roanne - Renaison",
    "LFLP Aeroport d'Annecy Haute-Savoie Mont Blanc",
    "LFLQ Aeroport de Montelimar - Ancone",
    "LFLR Aeroport de Saint-Rambert d'Albon",
    "LFLS Aeroport International de Grenoble Isere",
    "LFLT Aerodrome de Montlucon - Domerat",
    "LFLU Aeroport de Valence - Chabeuil",
    "LFLV Aeroport de Vichy - Charmeil",
    "LFLW Aeroport d'Aurillac",
    "LFLX Aeroport de Chateauroux - Deols",
    "LFLY Aeroport de Lyon Bron",
    "LFLZ Aerodrome de Feurs - Chambeon",
    "LFMA Aeroport d'Aix Les Milles",
    "LFMC Aeroport du Luc - Le Cannet",
    "LFMD Aeroport de Cannes - Mandelieu",
    "LFME Aeroport de Nimes Courbessac",
    "LFMF Aerodrome de Fayence",
    "LFMG Aerodrome de Montagne Noire",
    "LFMH Aeroport de Saint-etienne - Boutheon",
    "LFMI Base aerienne 125 d'Istres - Le Tube",
    "LFMK Aeroport de Carcassonne Salvaza",
    "LFML Aeroport de Marseille Provence",
    "LFMN Aeroport Nice Cote d'Azur",
    "LFMO Base aerienne 115 d'Orange Caritat",
    "LFMP Aeroport de Perpignan - Rivesaltes",
    "LFMQ Aeroport du Castellet",
    "LFMR Aeroport de Barcelonnette - Saint-Pons",
    "LFMS Aerodrome d'Ales Cevennes",
    "LFMT Aeroport Montpellier Mediterranee",
    "LFMU Aeroport de Beziers - Cap d'Agde en Languedoc",
    "LFMV Aeroport d'Avignon - Caumont",
    "LFMW Aeroport de Castelnaudary - Villeneuve",
    "LFMX Aeroport de Chateau Arnoux Saint-Auban",
    "LFMY Base aerienne 701 de Salon de Provence",
    "LFMZ Aerodrome de Lezignan Corbieres",
    "LFNA Aerodrome de Gap - Tallard",
    "LFNB Aerodrome de Mende - Brenoux",
    "LFNC Aeroport de Mont-Dauphin - Saint-Crepin",
    "LFND Aeroport de Pont - Saint - Esprit",
    "LFNE Aerodrome de Salon - Eyguieres",
    "LFNF Aeroport de Vinon",
    "LFNG Aeroport de Montpellier - Candillargues",
    "LFNH Aerodrome de Carpentras",
    "LFNJ Aerodrome d'Aspres sur Buech",
    "LFNL Aerodrome de Saint-Martin de Londres",
    "LFNN Aerodrome de Narbonne",
    "LFNO Aerodrome de Florac - Sainte-Enimie",
    "LFNP Aerodrome de Pezenas - Nizas",
    "LFNQ Aerodrome de Mont-Louis La Quillane",
    "LFNR Aerodrome de Berre - La Fare",
    "LFNS Aerodrome de Sisteron Theze",
    "LFNT Aerodrome d'Avignon - Pujaut",
    "LFNU Aerodrome d'Uzes",
    "LFNV Aerodrome de Valreas - Visan",
    "LFNW Aerodrome de Puivert",
    "LFNX Aerodrome de Bedarieux - La Tour-sur-Orb",
    "LFNZ Aerodrome du Mazet de Romanin",
    "LFOA Base aerienne 702 d'Avord",
    "LFOB Aeroport de Beauvais Tille",
    "LFOC Aeroport de Chateaudun",
    "LFOD Aerodrome de Saumur Saint-Florent",
    "LFOE Base aerienne 105 d'evreux - Fauville",
    "LFOF Aeroport d'Alencon - Valframbert",
    "LFOG Aeroport de Flers - Saint-Paul",
    "LFOH Aeroport du Havre - Octeville",
    "LFOI Aeroport d'Abbeville",
    "LFOJ Base aerienne 123 d'Orleans - Bricy",
    "LFOK Aeroport de Paris Vatry",
    "LFOL Aeroport de L'Aigle - Saint-Michel",
    "LFOM Aeroport de Lessay",
    "LFON Aerodrome de Dreux Vernouillet",
    "LFOO Aeroport Les sables - Talmont",
    "LFOP Aeroport Rouen Vallee de Seine",
    "LFOQ Aeroport de Blois - Le Breuil",
    "LFOR Aeroport de Chartres - Champhol",
    "LFOS Aeroport de Saint-Valery - Vittefleur",
    "LFOT Aeroport de Tours Val de Loire",
    "LFOU Aerodrome de Cholet Le Pontreau",
    "LFOV Aeroport de Laval - Entrammes",
    "LFOW Aerodrome de Saint-Quentin - Roupy",
    "LFOX Aeroport d'etampes Mondesir",
    "LFOY Aeroport du Havre - Saint-Romain",
    "LFOZ Aeroport d'Orleans - Saint-Denis de l'Hotel",
    "LFPA Aeroport de Persan - Beaumont",
    "LFPB Aeroport Paris - Le Bourget",
    "LFPC Base aerienne 110 de Creil",
    "LFPD Aeroport de Bernay - Saint-Martin",
    "LFPE Aeroport de Meaux - Esbly",
    "LFPF Aerodrome de Beynes - Thiverval",
    "LFPG Aeroport de Paris Charles de Gaulle",
    "LFPH Aeroport de Chelles le Pin",
    "LFPI Heliport de Paris - Issy-les-Moulineaux",
    "LFPK Aeroport de Coulommiers - Voisins",
    "LFPL Aeroport de Lognes - emerainville",
    "LFPM Base aerienne de Melun - Villaroche",
    "LFPN Aeroport de Toussus le Noble",
    "LFPO Aeroport Paris - Orly",
    "LFPP Aeroport du Plessis - Belleville",
    "LFPQ Aeroport de Fontenay - Tresigny",
    "LFPT Aeroport de Pontoise - Cormeilles-en-Vexin",
    "LFPU Aerodrome de Moret - episy",
    "LFPV Base aerienne 107 de Velizy Villacoublay",
    "LFPX Aerodrome de Chavenay - Villepreux",
    "LFPY Base aerienne 217 de Bretigny sur Orge",
    "LFPZ Aerodrome de Saint-Cyr l'ecole",
    "LFQA Aeroport de Reims - Prunay",
    "LFQB Aeroport de Troyes - Barberey",
    "LFQC Aeroport de Luneville - Croismare",
    "LFQD Aeroport d'Arras - Roclincourt",
    "LFQE Base aerienne d'etain - Rouvres",
    "LFQF Aeroport d'Autun Bellevue",
    "LFQG Aeroport de Nevers - Fourchambault",
    "LFQH Aeroport de Chatillon Sur Seine",
    "LFQI Base aerienne 103 de Cambrai - epinoy",
    "LFQJ Aeroport de Maubeuge - elesmes",
    "LFQK Aeroport de Chalons - ecury-sur-Coole",
    "LFQL Aeroport de Lens - Benifontaine",
    "LFQM Aeroport de Besancon - La Veze",
    "LFQN Aeroport de Saint-Omer - Wizernes",
    "LFQO Aeroport de Lille - Marcq-en-Baroeul",
    "LFQP Base aerienne de Phalsbourg - Bourscheid",
    "LFQQ Aeroport de Lille - Lesquin",
    "LFQS Aeroport de Vitry en Artois",
    "LFQT Aeroport de Merville - Calonne",
    "LFQU Aerodrome de Sarre Union",
    "LFQV Aeroport de Charleville-Mezieres - Belval",
    "LFQW Aeroport de Vesoul - Frotey",
    "LFQX Aerodrome de Juvancourt",
    "LFQY Aerodrome de Saverne - Steinbourg",
    "LFQZ Aerodrome de Dieuze - Gueblange",
    "LFRA Aerodrome d'Angers - Avrille",
    "LFRB Aeroport de Brest Bretagne",
    "LFRC Aeroport de Cherbourg - Maupertus",
    "LFRD Aeroport de Dinard Pleurtuit Saint-Malo",
    "LFRE Aeroport de La Baule Escoublac",
    "LFRF Aeroport de Granville Mont Saint-Michel",
    "LFRG Aeroport de Deauville - Saint-Gatien",
    "LFRH Aeroport de Lorient Bretagne Sud",
    "LFRI Aeroport de La Roche-sur-Yon - Les Ajoncs",
    "LFRJ Base d'aeronautique navale de Landivisiau",
    "LFRK Aeroport de Caen - Carpiquet",
    "LFRL Base d'aeronautique navale de Lanveoc - Poulmic",
    "LFRM Aeroport du Mans - Arnage",
    "LFRN Aeroport de Rennes - Saint-Jacques",
    "LFRO Aeroport de Lannion",
    "LFRP Aeroport de Ploermel - Loyat",
    "LFRQ Aeroport de Quimper Cornouaille",
    "LFRS Aeroport Nantes Atlantique",
    "LFRT Aeroport de Saint-Brieuc Armor",
    "LFRU Aeroport de Morlaix Ploujean",
    "LFRV Aeroport de Vannes - Meucon",
    "LFRW Aerodrome d'Avranches - Le Val Saint-Pere",
    "LFRZ Aeroport de Saint-Nazaire - Montoir",
    "LFSA Aeroport de Besancon - Thise",
    "LFSB Aeroport international Basel Mulhouse Freiburg",
    "LFSD Aeroport de Dijon Bourgogne - Longvic",
    "LFSE Aerodrome Epinal - Dogneville",
    "LFSF Base aerienne 128 de Metz Frescaty",
    "LFSG Aeroport d'epinal - Mirecourt",
    "LFSH Aerodrome d'Haguenau",
    "LFSI Base aerienne 113 de Saint-Dizier - Robinson",
    "LFSJ Aeroport de Sedan - Douzy",
    "LFSK Aeroport de Vitry-le-Francois - Vauclerc",
    "LFSL Aeroport de Brive Vallee de la Dordogne",
    "LFSM Aeroport de Montbeliard - Courcelles",
    "LFSN Aeroport de Nancy - Essey",
    "LFSO Base aerienne 133 de Nancy - Ochey",
    "LFSP Aerodrome de Pontarlier",
    "LFSR Aeroport de Reims Champagne",
    "LFST Aeroport de Strasbourg Entzheim",
    "LFSU Aeroport de Langres - Rolampont",
    "LFSV Aerodrome de Pont Saint-Vincent",
    "LFSW Aeroport d'epernay - Plivot",
    "LFSX Base aerienne 116 de Luxeuil - Saint-Sauveur",
    "LFSZ Aeroport de Vittel Champ de courses",
    "LFTF Aeroport de Cuers - Pierrefeu",
    "LFTH Aeroport de Toulon - Hyeres - Le Palyvestre",
    "LFTL Heliport de Cannes - Quai du large",
    "LFTM Aerodrome de Serres - La Batie-Montsaleon",
    "LFTN Aerodrome de La Grand'Combe",
    "LFTP Aerodrome de Puimoisson",
    "LFTQ Aerodrome de Chateaubriant - Pouance",
    "LFTW Aeroport de Nimes - Garons",
    "LFTZ Aeroport de La Mole - Saint-Tropez",
    "LFXA Aerodrome d'Amberieu",
    "LFXB Aeroport de Saintes - Thenac",
    "LFXI Base aerienne 200 Apt - Saint-Christol",
    "LFXM Aerodrome de Mourmelon",
    "LFXU Aeroport des Mureaux",
    "LFYD Aeroport de Damblain",
    "LFYG Aerodrome de Cambrai - Niergnies",
    "LFYH Aeroport de Broyes les Pesmes",
    "LFYM Aeroport de Marigny Le Grand",
    "LFYR Aeroport de Romorantin - Pruniers",
    "LFYS Aerodrome de Sainte-Leocadie",
    "LFYT Base aerienne de Saint-Simon - Clastres",
    "SOCA Aeroport de Cayenne - Rochambeau",
    "SOGS Aerodrome de Grand Santi",
    "SOOA Aerodrome de Maripasoula",
    "SOOG Aerodrome de Saint-Georges de l'Oyapock",
    "SOOK Aerodrome de Kourou",
    "SOOM Aerodrome de Saint Laurent du Maroni",
    "SOOR Aerodrome de Regina",
    "SOOS Aerodrome de Saul",
    "TFFA Aerodrome de la Desirade - Grande Anse",
    "TFFB Aerodrome de Basse Terre - Baillif",
    "TFFC Aerodrome de Saint Francois",
    "TFFF Aeroport de Martinique - Aime Cesaire",
    "TFFG Aerodrome de Grand Case Esperance",
    "TFFJ Aerodrome de Saint Barthelemy",
    "TFFM Aerodrome de Grand Bourg",
    "TFFR Aeroport de Guadeloupe - Pole Caraibes",
    "TFFS Aerodrome Les Saintes - Terre de Haut",
    "TTFG Aeroport de Saint-Martin Grand Case"
};

size_t nstrings = sizeof(strings)/sizeof(char*);


#endif /* DATA_H */
